### ISSUE TITLE
Update the admin to unsuck it a bit

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#125]
- [x] ContractBase should be a bit cleaner
  - [x] Be more judicious with the fields that are displayed
  - [x] Rewrite some of the headers
- [x] Figure out a way to do link out of the admin up to the main app navbar. (BONUS: Figure out a way to link to an individual contract entity)
