### ISSUE TITLE
Phone/Tablet Testing Screenshots

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#167]
Computers (everything, including admin):
- ~~Your Mac~~
- [ ] See if we can dig up a monitor with the dimensions/resolution from the city. Maybe Laura can send us a screencap?

Tablet (everything, including admin):
- [ ] iPad
- [ ] iPad Mini

Phone (public-facing stuff only):
- [ ] iPhone 4
- [ ] iPhone 5
- [ ] iPhone 6
- [ ] iPhone 6+
- [ ] Galaxy s3
- [ ] Galaxy s4
- [ ] Galaxy Note 3

**Comment by hamhands** [comment]
City computer monitor, possibly reasonable facsimile: <img width="864" alt="screen shot 2015-08-03 at 11 54 26 am" src="https://cloud.githubusercontent.com/assets/3640800/9045200/72c0164c-39d6-11e5-909b-4936d4c3508f.png">

**Comment by hamhands** [comment]
City computer, possibly reasonable facsimile of resolution/dimensions:
<img width="869" alt="screen shot 2015-08-03 at 11 57 31 am" src="https://cloud.githubusercontent.com/assets/3640800/9045296/ebd8d938-39d6-11e5-9034-3b4f6ad56d41.png">

**Comment by hamhands** [comment]
### iPad

Subscrib:
<img width="646" alt="screen shot 2015-08-03 at 2 44 38 pm" src="https://cloud.githubusercontent.com/assets/3640800/9048449/38597652-39ee-11e5-8e85-343d2bbe3930.png">

Slight table wonkiness on landscape: 
<img width="645" alt="screen shot 2015-08-03 at 12 00 03 pm" src="https://cloud.githubusercontent.com/assets/3640800/9045339/452b91e2-39d7-11e5-9c01-b1d17f8204e5.png">
Dramatic margins on portrait. Do we want mobile to kick at this width?
<img width="388" alt="screen shot 2015-08-03 at 12 00 30 pm" src="https://cloud.githubusercontent.com/assets/3640800/9045338/4529472a-39d7-11e5-9a89-4f4252b809da.png">
Mobile dropdown on portrait:
<img width="389" alt="screen shot 2015-08-03 at 1 15 01 pm" src="https://cloud.githubusercontent.com/assets/3640800/9046737/aed8549a-39e1-11e5-9c24-d1e787586ff0.png">

Admin looks fine on both portrait and landscape:
<img width="393" alt="screen shot 2015-08-03 at 1 19 05 pm" src="https://cloud.githubusercontent.com/assets/3640800/9046818/3fcff840-39e2-11e5-9dd3-9aeb54ee1c76.png">

**Comment by hamhands** [comment]
### iPad Mini

Same issues as iPad, admin fine.

**Comment by hamhands** [comment]
### iPhone 4/5

Splash looks pretty huge, needs some top padding. Also too big for the call to action to fit:
<img width="316" alt="screen shot 2015-08-03 at 1 20 27 pm" src="https://cloud.githubusercontent.com/assets/3640800/9046850/8f61537c-39e2-11e5-8257-475d5c59eb12.png">

Nav dropdown still a bit wonky, not as bad as ipad:
<img width="315" alt="screen shot 2015-08-03 at 1 21 08 pm" src="https://cloud.githubusercontent.com/assets/3640800/9046872/b39386de-39e2-11e5-80d7-e5c81fae60fe.png">

Footer all stubby:
<img width="318" alt="screen shot 2015-08-03 at 1 27 04 pm" src="https://cloud.githubusercontent.com/assets/3640800/9046968/64df736c-39e3-11e5-8e8b-80180c810cd3.png">

Text hierarchy off:
<img width="316" alt="screen shot 2015-08-03 at 1 27 57 pm" src="https://cloud.githubusercontent.com/assets/3640800/9046986/83c73b5c-39e3-11e5-9629-732835df845b.png">

**Comment by hamhands** [comment]
### iPhone 6/6+

Same as above, without splash issues

**Comment by hamhands** [comment]
### Galaxy S3

Same as above

### Galaxy S4 & Note

Same as above, minus splash issues

**Comment by hamhands** [comment]
### Tasks
* [ ] fix button issue for tablets
* [ ] decrease margins for tablets, especially in portrait mode
* [ ] unsuck mobile navbar dropdown
* [ ] decrease splash text size for smaller smartphones
* [ ] add some padding for mobile splash
* [ ] decrease margin on opportunities page

**Comment by hamhands** [comment]
### Tasks
* [ ] fix button issue for tablets
* [ ] decrease margins for tablets, especially in portrait mode
* [ ] unsuck mobile navbar dropdown
* [ ] decrease splash text size for smaller smartphones
* [ ] add some padding for mobile splash
* [ ] decrease margin on opportunities page

**Comment by bsmithgall** [comment]
@hamhands i'm going to open a second issue to keep track of those tasks.

**Comment by hamhands** [comment]
@bsmithgall :ok_hand: :ok_woman: :+1: :ok:

**Comment by bsmithgall** [comment]
@hamhands can you verify this works on your phone on staging/production? If so, feel free to close this issue. #178 still needs to be resolved, though.

**Comment by hamhands** [comment]
@bsmithgall :+1: 
![image](https://cloud.githubusercontent.com/assets/3640800/9100878/a210c256-3b94-11e5-8cf6-ba5f13152e29.png)

**Comment by hamhands** [comment]
See #183
