### ISSUE TITLE
Scrape County Closed Bids for Pricing Data

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#17]
### TODO
- [x] Selenium script to parse things
- [x] Some sort of flag to determine if a contract has been crawled or not
- [x] Save data into model DB

Related to #9 (maybe replaces?)

**Comment by bsmithgall** [comment]
[Closed solicitations](http://www.govbids.com/scripts/PAPG/public/OpenBids/ViewSolicitations.asp?Agency=1100&AgencyName=Allegheny+County+-+Division+of+Purchasing+and+Supplies)

**Comment by bsmithgall** [comment]
TODO:
- [x] Figure out if we have this contract (spec # search? description fuzzy search? both?)
- [x] Import data into the database
