### ISSUE TITLE
CSS Tweaks for beacon

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#170]
### Tasks
- [x] fix button issue for tablets
- [x] decrease margins for tablets, especially in portrait mode
- [ ] unsuck mobile navbar dropdown
- [x] decrease splash text size for smaller smartphones
- [x] add some padding for mobile splash
- [x] decrease margin on opportunities page
- [x] mobile table issues
