### ISSUE TITLE
Data upload party!

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#209]
BACK UP YOUR DATABASE!

We're going to put the site into maintenance mode at 3pm eastern on Thursday, August 13 for an estimated three-hour maintenance window.

**Comment by bsmithgall** [comment]
TODO:
- [x] Export all COSTARS contracts from mega-excel to series of CSVs
- [x] Upload all COSTARS pdfs to S3 
- [x] Combine all contract types from old x-drive spreadsheet into one spreadsheet (csv)
- [x] Back up database 
- [x] Move app into maintenance mode 
- [x] Nuke old contract data
- [x] Upload new costars contracts
- [x] Upload all other contracts
- [x] Scrape county for line items

**Comment by bsmithgall** [comment]
This is alllll done.
