### ISSUE TITLE
Global email reminder/notification strategy for Scout/Conductor & Beacon

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#210]
### Scout

**Expiration**
- [x] If OMB has not started work on the contract, 120 days before it expires (Nightly)
- [x] When it expires (Nightly)
- [ ] When OMB starts work on the contract (Nice to have feature, will be captured in new issue -- A state-based notification flag) (Transact)

**Metadata**
- [x] When a contract you follow has been extended/renewed (Transact)
- [ ] When the controller/spec number has been updated (TODO: Check w/Riley about this) (Transact)
- [ ] When a new company is added or removed (Transact)
- [ ] When new line items are added (Transact)

**Other**
- [x] When someone sends feedback to the feedback form (Transact)
### Beacon

**Vendors**
- [x] On signup (Transact)
- [x] On new opportunity advertised for category you are subscribed to (Transact/Nightly)
- [x] On subscription to opportunity/opportunities (Transact)
- [x] When an opportunity you follow/in a category you subscribe to opens (Nightly)
- [ ] Five days before an opportunity you follow/in a category you subscribe to will close  (Nightly)
- [ ] The day before an opportunity you follow/in a category you subscribe to will close (Nightly)
- [ ] When a new document is uploaded to an opportunity you follow (in a category you subscribe to as well?) (Transact)
- [x] Biweekly digest of all opportunities (Nightly)

**Admin**
- [ ] Weekly digest of the signups that week (Nightly) (To: Conductor+)
- [x] New Opportunity Created (Transact) (To: Conductor+)
- [x] Opportunity is approved by OMB (Transact) (To: Creator, Contact)
- [x] Opportunity has been submitted to OMB (Transact) (To: Creator, Contact)
- [ ] The opp you created is now open (Nightly) (To: Creator, Contact)
- [ ] The opp you created will close tomorrow (Nightly) (To: Creator, Contact)

This will close #39 as a duplicate. #38 and #27 are pre-requisites for work to be started on this.

**Comment by msknee** [comment]
Progress today: wrote html and txt files for all transactional admin emails for Beacon today. 

Email copy is here: https://docs.google.com/document/d/1nBqy2BBJKAw6KOL1yu2rSEtbBLJrqpKust-2ugXrRng/edit#

**Comment by bsmithgall** [comment]
Question about these -- there is a lot of potential for multiple conditions to be true, especially with Beacon when you get many opportunities up and running. How should the jobs handle this? Should there be one email per day maximum? One email per event? This will affect how the nightly job runner gets built.

**Comment by msknee** [comment]
@bsmithgall I thiiiink one email per event. Better to be make sure everyone gets notified about an opp at the same time but have a lot of emails going out, than someone not receiving word about something because they were subscribed to something else that sent out an email that day. Also, very few people will be subscribed to the max amount of categories and inundated with emails.

Is there a way to do a daily digest without too much work?

**Comment by bsmithgall** [comment]
:+1: 

Which ones above are required for launch? I think that the bi-weekly digest is the last remaining one that needs to be written.

**Comment by msknee** [comment]
@bsmithgall yeah, that one. workin' on it today!

**Comment by msknee** [comment]
Procurement staff didn't want additional notifications going out, so I'm closing this issue as is.
