### ISSUE TITLE
Conductor Problem Dump

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#226]
#### Bugs / major points of confusion

**Contract list**
- [x] Easily filter or switch between contracts I'm working on, and contracts everyone else is working on
- [ ] Once I extend a contract, I expect that it will continue to be assigned to me, since I will still need to shepherd it through. It was confusing when I was unassigned from the extended contract. (added to #227: Questions for Ed)
- [ ] Extended contracts also start back at step 1. They should continue at the step they were at when they are extended. (added to #227: Questions for Ed)
- [x] I completed a contract all the way through Conductor, and set the expiration date to today. When I assigned it to myself again, it won't show up in "In progress" contracts even though I get success messages and it's assigned to me in the admin. Same bug that @hamhands reported.

![conductor_qa4](https://cloud.githubusercontent.com/assets/1178390/9319228/f3978a22-4500-11e5-8365-ac77c404ea78.gif)

**Detail view**
- [x] Original contract metadata (using department, old spec #, old controller #, and most importantly, old expiration date) does not carry over to metadata tab
- [x] ^^ Replicated @hamhands' update metadata bug above
- [x] Error page when submitting "Post from Beacon" form:

![conductor_qa3](https://cloud.githubusercontent.com/assets/1178390/9318790/fe6f7a4a-44fb-11e5-8a08-9e2cf157f78b.gif)

**Editing contract when done**
- [x] Edge case? After I click the "X" button to get rid of a new company card, clicking "Add another" button doesn't generate another company card.
- [x] After I click the "X" button to get rid of a company card, it reappears when I try to submit the company form and prevents me from proceeding.

![screen shot 2015-08-17 at 4 47 52 pm](https://cloud.githubusercontent.com/assets/1178390/9319150/0fe85e14-4500-11e5-9cdd-e67326bc6fc9.png)
#### UX tweaks

**Contract List**
- [x] Zoom in icon doesn't communicate "click here to work on this contract" as well as I thought it would. Alternatives: 
- Change zoom in icon to "Update" button
- Turn contract name into a button
- [x] Assign dropdown should be styled the same as Actions dropdown

**Detail view**
- [x] Title div across top of the page, with contract title, link to edit contract info, and option to switch contract flow if applicable
- [x] Separate out actions specific to the stage from the dropdown: extend for 90 days
- [x] Title text overlaps with Revert button

![screen shot 2015-08-17 at 4 27 19 pm](https://cloud.githubusercontent.com/assets/1178390/9318853/f0c5595e-44fc-11e5-9b38-2a01ebdd3cb1.png)

**Editing contract when done**
- [x] Choosing between an existing company and a new one is still confusing, because they're on the same card. Simple tweak:
- Take the instructions off of the card and put them above it in h1 type
- Display 1 card that contains fields for adding an existing company
- Have 1 button that says "Add another existing company"
- Have 1 button underneath that one that says "Add a new company"
#### Copy tweaks
- [ ] Input County and Departmental email addresses into Staging
- [x] Change Wexplorer to Scout:
  ![screen shot 2015-08-17 at 4 29 52 pm](https://cloud.githubusercontent.com/assets/1178390/9318887/414ee3c2-44fd-11e5-966e-176f11b6c213.png)

**Comment by hamhands** [comment]
### Update metadata bug:

![metadata_bug](https://cloud.githubusercontent.com/assets/3640800/9318539/3e5a3422-44f9-11e5-8401-dffc4732e535.gif)

**Comment by hamhands** [comment]
Not really a bug, but this seems like an _antagonistic_ form to me:
![weird_flow](https://cloud.githubusercontent.com/assets/3640800/9318619/028f8b8a-44fa-11e5-970f-879d5e7999f5.gif)

**Comment by bsmithgall** [comment]
Lol. What should it say?

**Comment by msknee** [comment]
#### Bugs / major points of confusion

**Contract list**
- [x] Easily filter or switch between contracts I'm working on, and contracts everyone else is working on
- [ ] Once I extend a contract, I expect that it will continue to be assigned to me, since I will still need to shepherd it through. It was confusing when I was unassigned from the extended contract. (added to #227: Questions for Ed)
- [ ] Extended contracts also start back at step 1. They should continue at the step they were at when they are extended. (added to #227: Questions for Ed)
- [x] I completed a contract all the way through Conductor, and set the expiration date to today. When I assigned it to myself again, it won't show up in "In progress" contracts even though I get success messages and it's assigned to me in the admin. Same bug that @hamhands reported.

![conductor_qa4](https://cloud.githubusercontent.com/assets/1178390/9319228/f3978a22-4500-11e5-8365-ac77c404ea78.gif)

**Detail view**
- [x] Original contract metadata (using department, old spec #, old controller #, and most importantly, old expiration date) does not carry over to metadata tab
- [x] ^^ Replicated @hamhands' update metadata bug above
- [x] Error page when submitting "Post from Beacon" form:

![conductor_qa3](https://cloud.githubusercontent.com/assets/1178390/9318790/fe6f7a4a-44fb-11e5-8a08-9e2cf157f78b.gif)

**Editing contract when done**
- [x] Edge case? After I click the "X" button to get rid of a new company card, clicking "Add another" button doesn't generate another company card.
- [x] After I click the "X" button to get rid of a company card, it reappears when I try to submit the company form and prevents me from proceeding.

![screen shot 2015-08-17 at 4 47 52 pm](https://cloud.githubusercontent.com/assets/1178390/9319150/0fe85e14-4500-11e5-9cdd-e67326bc6fc9.png)

#### UX tweaks

**Contract List**
- [x] Zoom in icon doesn't communicate "click here to work on this contract" as well as I thought it would. Alternatives: 
- Change zoom in icon to "Update" button
- Turn contract name into a button
- [x] Assign dropdown should be styled the same as Actions dropdown

**Detail view**
- [ ] Title div across top of the page, with contract title, link to edit contract info, and option to switch contract flow if applicable
- [ ] Separate out actions specific to the stage from the dropdown: extend for 90 days
- [ ] Title text overlaps with Revert button

![screen shot 2015-08-17 at 4 27 19 pm](https://cloud.githubusercontent.com/assets/1178390/9318853/f0c5595e-44fc-11e5-9b38-2a01ebdd3cb1.png)

**Editing contract when done**
- [x] Choosing between an existing company and a new one is still confusing, because they're on the same card. Simple tweak:
- Take the instructions off of the card and put them above it in h1 type
- Display 1 card that contains fields for adding an existing company
- Have 1 button that says "Add another existing company"
- Have 1 button underneath that one that says "Add a new company"

#### Copy tweaks
- [ ] Input County and Departmental email addresses into Staging
- [x] Change Wexplorer to Scout:
  ![screen shot 2015-08-17 at 4 29 52 pm](https://cloud.githubusercontent.com/assets/1178390/9318887/414ee3c2-44fd-11e5-966e-176f11b6c213.png)

**Comment by hamhands** [comment]
@bsmithgall maybe a new vendor vs. existing vendor radio button, then the form

**Comment by hamhands** [comment]
### Weird problem with assigning:

![not_assigning](https://cloud.githubusercontent.com/assets/3640800/9318849/ea17f508-44fc-11e5-8e33-fdf52ce2d09d.gif)

I think it's not assigning contracts I added in the admin for some reason.

**Comment by bsmithgall** [comment]
@hamhands can you check in the admin to see if those contracts are actually assigned?

**Comment by hamhands** [comment]
Yes, they are: 
<img width="1167" alt="screen shot 2015-08-17 at 4 32 22 pm" src="https://cloud.githubusercontent.com/assets/3640800/9318912/90c1f0b6-44fd-11e5-8f7b-4c5bf746e263.png">

**Comment by bsmithgall** [comment]
I think it's a weird artifact that's come about from the previous problem with them not showing up.

**Comment by hamhands** [comment]
When do weird artifacts end and bugs begin???

**Comment by hamhands** [comment]
~\* philosophy questions *~

**Comment by bsmithgall** [comment]
@shellicious what do you mean about "styled the same" -- the dropdown should have icons? Maybe this one? http://fontawesome.io/icon/user/

**Comment by msknee** [comment]
@bsmithgall I meant the dropdown should be white with a border

**Comment by bsmithgall** [comment]
Some additional notes:
- The bug referenced about re-assigning contracts is happening because re-assigned contracts aren't properly cloning. I need to investigate why they aren't being cloned.
- The filter-by-user thing might take a bit longer than expected with datatables.
- The card split should be _fairly_ straightforward, though could be a total k-hole.

**Comment by bsmithgall** [comment]
Sketch of title view

![sketch of title bar for contract detail biew](https://cloud.githubusercontent.com/assets/1957344/9321788/ab6b04bc-451f-11e5-81ea-b0665e6cfe82.jpg)

**Comment by bsmithgall** [comment]
![screen shot 2015-08-17 at 8 43 43 pm](https://cloud.githubusercontent.com/assets/1957344/9321871/adc224ce-4520-11e5-8e12-6fe22c3d7412.png)

Update button. Thoughts @shellicious ?

**Comment by msknee** [comment]
Better than the zoom in icon; better still if it were the one button on the page that got colored (light gray for not-about-to-expire, red and orange for closer to expiration)

**Comment by bsmithgall** [comment]
That's the in-progress table though, so it doesn't have expiration. Would you want that coloration to replace the current yellow/red color scheme?

**Comment by bsmithgall** [comment]
How's this, RE companies?

![autom8](https://cloud.githubusercontent.com/assets/1957344/9322210/d7511328-4524-11e5-8d5b-f434dc9ee8de.gif)

**Comment by msknee** [comment]
@bsmithgall yassss :100:

**Comment by bsmithgall** [comment]
Current detail view (with proto-title card)

![screen shot 2015-08-18 at 11 33 45 am](https://cloud.githubusercontent.com/assets/1957344/9339087/05004cbc-459d-11e5-80f4-d63f01413c55.png)

**Comment by bsmithgall** [comment]
Current revert view

![screen shot 2015-08-18 at 11 36 04 am](https://cloud.githubusercontent.com/assets/1957344/9339157/571ed5c2-459d-11e5-958a-dbfef5b17ef8.png)

**Comment by msknee** [comment]
New detail view:

![detailpage_current](https://cloud.githubusercontent.com/assets/1178390/9342093/be469ada-45ae-11e5-88b6-93649f4495b2.png)

New revert view:

![detailpage_revert](https://cloud.githubusercontent.com/assets/1178390/9342103/c6c7faf0-45ae-11e5-8b41-f788fe989705.png)

**Comment by msknee** [comment]
@bsmithgall ^^ (ignore the weird black line at the bottom)

**Comment by bsmithgall** [comment]
@shellicious @hamhands I'd like to close/merge this mega issue w/#229. Can we open new issues for inputting the stuff into conductor-staging, and for fixing the "extend" so that it works as expected (that might be a bit tricky with the current workflow)?

**Comment by msknee** [comment]
@bsmithgall yup, will open 2 issues:
- inputting contacts into staging
- fixing contract extension workflow
