### ISSUE TITLE
Add selenium tests for JS-heavy bits of the UI

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#255]
Here are some obvious candidates:
- [ ] Conductor company/contact bit
- [ ] Conductor emails
- [ ] Anything with advanced charts/graphs
- [ ] Beacon categories stuff

**Comment by ajb** [comment]
This issue was ~~moved~~ copied to dobtco/beacon#2
