### ISSUE TITLE
Prepare for THE LAUNCH OF BEACON

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#313]
:rocket: :rocket: :rocket: :rocket: 

**General notes:**
- Sync up with Geoff/John about getting into the actual roadmap documents (should happen Aug 28).
- Reach out to OMB to discuss implications of advanced timeline

**TODO - Code:**
- [x] Issue #305
- [x] Issue #306 
- [x] Issue #210 and related

**TODO - Not code:**
- [x] Provide a paragraph to the Mayor's office with a description of Beacon
- [x] Prep for 5min introduction to Beacon @ innovation roadmap kickoff event
- [x] Prep one (1) slide to be displayed while Beacon is discussed (Due Thursday 9/3)
- [x] Prep one (1) sentence for the roadmap kickoff agenda (Due Monday 8/31)
- [x] Write an internal announcement for OMB to announce that they should direct people to Beacon
- [x] Image for city to share on social media (FB / Twitter)

:moon: :moon: :moon: :moon:

**Comment by bsmithgall** [comment]
We also need to sync up with Henry about
- places/people to talk to about publicizing Beacon
- replacement or supplemental information for the small businesses resource fair, possibly call in remotely? @hamhands has committed us to remote presentation, maybe we should just send someone back...

**Comment by bsmithgall** [comment]
Let's actually try to send someone, I think we have budget for it...

**Comment by hamhands** [comment]
Alternatively @shellicious or I could just stay for three weeks? Is that
awful?

On Fri, Aug 28, 2015 at 12:03 PM, Ben Smithgall notifications@github.com
wrote:

> Let's actually try to send someone, I think we have budget for it...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/pittsburgh-purchasing-suite/issues/313#issuecomment-135815289
> .

## 

Patrick Hammons
@hamhandedly

**Comment by msknee** [comment]
we def have budget to send someone back for a couple days around the 23rd. 

Collaborating on summit and building things up til launch will be compromised if 2 of us are in Pittsburgh for 3 weeks. Like, we are capable of doing it, but I feel like we're more productive when we're all in the same place.

**Comment by msknee** [comment]
@bsmithgall @hamhands what's the format for the slide due on 9/3? PDF, PPT, Keynote, doesn't matter as long as it is slide-shaped?

**Comment by bsmithgall** [comment]
I think we'll get an email later today, but it sounded like PPT

**Comment by bsmithgall** [comment]
Also let's send things to the folks over at the riverside center!

**Comment by msknee** [comment]
Spreadsheet for individual businesses & orgs to contact: https://docs.google.com/a/codeforamerica.org/spreadsheets/d/1V54Eo-ZDUj_A29Kg3BrMDQex7dAs2wV8q7cKxHdHYS0/edit?usp=drive_web

**Comment by msknee** [comment]
First pass at launch event copy here: https://docs.google.com/document/d/12YvUWZ2xZceTFeqq64NRzXEu_QYR_Y7TwCjwYCI026M/edit# @bsmithgall @hamhands

**Comment by hamhands** [comment]
@bsmithgall @shellicious copy sent to the mayor's office this morning. :white_check_mark:

**Comment by msknee** [comment]
@hamhands send out email to Shawn Hicks (AACC), Henry at OMB, Rebecca at Chatham, and Judy at Riverside asking them to send out a blurb on Tuesday 9/8. Blurb should have flyer for Beacon attached, AND info about event (FREE FOOD + RSVP link) as a PS.

**Comment by bsmithgall** [comment]
Welp, I think this is FINISHED.

:rocket: :rocket: :rocket: :rocket: 

@shellicious @hamhands feel free to close it after the press conference!
