### ISSUE TITLE
Start times for nightly jobs

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#345]
I propose a job start time of 7am EST for all of the nightly jobs. 
### Scout

**Expiration**
- [ ] If OMB has not started work on the contract, 120 days before it expires (Nightly)
- [ ] When it expires (Nightly)
### Beacon

**Vendors**
- [ ] On new opportunity advertised for category you are subscribed to (Transact/Nightly)
- [ ] When an opportunity you follow/in a category you subscribe to opens (Nightly)
- [ ] Five days before an opportunity you follow/in a category you subscribe to will close  (Nightly)
- [ ] The day before an opportunity you follow/in a category you subscribe to will close (Nightly)
- [ ] Biweekly digest of all opportunities (Nightly)

**Admin**
- [ ] Weekly digest of the signups that week (Nightly) (To: Conductor+)
- [ ] The opp you created is now open (Nightly) (To: Creator, Contact)
- [ ] The opp you created will close tomorrow (Nightly) (To: Creator, Contact)

**Comment by bsmithgall** [comment]
:+1:
