### ISSUE TITLE
Schedule folks for 10/12-10/15

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#468]

**Comment by msknee** [comment]
- [x] Sam Ashbaugh + Jennifer + Riley + Stephanie + Ed prioritization meeting, Tuesday 10/13. @rileystewart will schedule.
- [x] 1:1 time with Ed
- [x] 1:1 time with Stephanie
- [x] 1:1 time with Riley
- [x] Syliva + Laura to discuss transfer to pittsburghpa.gov and maintenance options
- [x] Webteam + Laura to discuss transfer to pittsburghpa.gov
- [x] Sam Ashbaugh + Jennifer to discuss adding authorities to Beacon, Thursday 10/15.

**Comment by msknee** [comment]
@bsmithgall @hamhands who else do we need to meet with to discuss transfer to pittsburghpa.gov URL and maintenance?
