### ISSUE TITLE
Transfer PGH Procurement Suite to pittsburghpa.gov

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#481]
- [x] Sylvia approves
- [x] Initiate contracting process for Ben
- [x] Submit help ticket for procurement.pittsburghpa.gov URLs
- [x] Document external links for web team
- [ ] Transfer Heroku
- [x] Transfer Sendgrid
- [x] Transfer AWS
- [ ] Transfer Typeform

**Comment by bsmithgall** [comment]
Typeform? I think the order of operations here is also a bit backwards:
1. We don't want to transfer ownership of the accounts until we've figured out what the maintenance agreement looks like.
2. The URL transfer is going to be the hardest part. Are we looking for a subdomain? If so, how do we want to handle everything?

**Comment by msknee** [comment]
feel free to edit the original to-do checklist! made this so that there's something to reference from the Trello board

**Comment by msknee** [comment]
Met with Sylvia today. She wants a version of this (https://docs.google.com/document/d/1JkKIvI1ejcV-vHDGeITE3bvJQd-HQs4kaPuvnK9l1gc/edit) detailing what the maintenance and bundled services are for, and monthly costs of different options. 

She and Jim at I&P will discuss, then they'll send us their ideal option. They'll reach out to OMB to figure out how to pay for it.

**Comment by msknee** [comment]
Sam approves of the Ben option. Meeting next week to discuss logistics with @rileystewart and Jennifer.

**Comment by bsmithgall** [comment]
Additional things to do:

Email:
- [ ] change outgoing emails to come from @pittsburghpa.gov
- [ ] have pittsburgh folks properly set outgoing mail servers as valid (SPF/DKIM/etc) for sendgrid
- [x] set the default outbound email addresses for beacon to deliver to omb

Web:
- [x] Have city upload wildcard cert to heroku
- [x] Reconfigure app to point to the .gov url
- [ ] Have Mike sunset buildpgh.com and redirect it to the .gov URL
