### ISSUE TITLE
Planning meetings for 11/2-6

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#559]
- [x] Laura / Sam handover meeting (@bsmithgall can you take this one?)
- [x] Tuesday press conference
- [x] Go over metrics page 
- [x] Lunches / breakfasts (@shellicious will do)
  - [x] Ed / Stephanie
  - [x] Riley / Jenn / Sam
  - [x] Paz / Laura
  - [x] Slim
  - [x] Web team
  - [x] Geoff / Tara
  - [x] ...

**Comment by msknee** [comment]
Emailed everyone, waiting for responses. I've placed holds on the calendar to reflect availability.
