### ISSUE TITLE
Administrative checklist for transfer of tools

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#579]
- [x] OMB creates proxy email that forwards questions to @rileystewart: procurement@pittsburghpa.gov
- [x] Update pittsburgh@codeforamerica.org with proxy email address on walkthroughs
- [x] Update pittsburgh@codeforamerica.org with same proxy email on Beacon
- [ ] Add procurement.pittsburghpa.gov URLs to Intranet

**Comment by bsmithgall** [comment]
Other open questions:
- [x] Who owns the Heroku/AWS/Sendgrid accounts?
- [x] Which version of the codebase are we going to be running? The one under the CFA repo? A fork to a I&P repo?

**Comment by msknee** [comment]
Answers to above: I&P, @laurameixell setting them up
