### ISSUE TITLE
Things to do before July user testing

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#88]
### Required tasks
- [x] do rest of work around NIGP codes
- [x] finish beacon launch plan
- [x] interview questions
- [x] backend category adding for beacon
- [x] content for law meeting
- [x] write soft-launch email for Henry and Kevin to forward
- [x] fix staging site login
- [x] add a bunch of stages to conductor
- [ ] look over confirmation email for beacon 
### Stretch tasks
- [ ] page on beacon w/content from Claire's RFP
